spring.application.name=sms_provider

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/sms_provider
spring.datasource.username=sms_provider_db
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


